training:
  batch_size: [4, 8, 8]
  batch_size_val: 32
  const_max: 2
  gamma: 0.5
  n_epochs_warmup: 50
  num_workers: 12
  n_epochs: 200
  early_stop_patience: 10
  reduce_lr_patience: 5
  accumulate_batches: 1
  gradient_clip: 5
  save_top_k: 1
  median_window: 7
data:
  synth_folder: ""
  synth_tsv: ""
  weak_folder: ""
  weak_tsv: ""
  unlabeled_folder: ""
  audio_max_len: 10
  fs: 16000
  net_subsample: 4
opt:
  lr: 0.001
feats:
  n_mels: 128
  n_filters: 2048
  kernel_size: 2048
  stride: 256
  window: hanning
  fmin: 0
  fmax: 8000
