training:
  #batch size: [synth, weak, unlabel]
  batch_size: [6, 6, 12]
  batch_size_val: 24
  const_max: 2
  n_epochs_warmup: 50
  num_workers: 6
  n_epochs: 200
  early_stop_patience: 10
  accumulate_batches: 1
  gradient_clip: 0
  median_window: 7
  val_thresholds: [0.5]
  n_test_thresholds: 50
  ema_factor: 0.999
  self_sup_loss: mse
  backend:
  noise_snr: [12, 15]
  validation_interval: 1
  weak_split: 0.9
  seed: 28
scaler:
  statistic: dataset
  normtype: mvn
  dims: [0, 2]
  savepath: ./scaler.ckpt
data:
  synth_folder: "../../data/dcase2020/audio/train/synthetic20_train/soundscapes_16k/"
  synth_tsv:  "../../data/dcase2020/metadata/train/synhtetic20_train/soundscapes.tsv"
  weak_folder: "../../data/dcase2021/dataset/audio/train/weak_16k/"
  weak_tsv: "../../data/dcase2021/dataset/metadata/train/weak.tsv"
  unlabeled_folder: "../../data/dcase2021/dataset/audio/train/unlabel_in_domain_16k/"
  synth_val_folder: "../../data/dcase2020/audio/validation/synthetic20_validation/soundscapes_16k/"
  synth_val_tsv:  "../../data/dcase2020/metadata/validation/synhtetic20_validation/soundscapes.tsv"
  synth_val_dur: "../../data/dcase2020/metadata/validation/synhtetic20_validation/durations.tsv"
  test_folder: "/disks/disk1/dcase/dataset/audio/validation_16k/"
  test_tsv: "/disks/disk1/dcase/dataset/metadata/validation/validation.tsv"
  test_dur: "/disks/disk1/dcase/dataset/metadata/validation/validation_durations.tsv"
  audio_max_len: 10
  fs: 16000
  net_subsample: 4
opt:
  lr: 0.001
feats:
  n_mels: 128
  n_filters: 2048
  #  kernel_size: 2048
  hop_length: 256
  n_window: 2048
  sample_rate: 16000
  f_min: 0
  f_max: 8000
net:
  dropout: 0.5
  rnn_layers: 2
  n_in_channel: 1
  nclass: 10
  attention: True
  n_RNN_cell: 128
  activation: glu
  rnn_type: BGRU
  kernel_size: [3, 3, 3, 3, 3, 3, 3]
  padding: [1, 1, 1, 1, 1, 1, 1]
  stride: [1, 1, 1, 1, 1, 1, 1]
  nb_filters: [ 16, 32, 64, 128, 128, 128, 128 ]
  pooling: [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ] ]
  dropout_recurrent: 0
