training:
  batch_size: [24, 24, 24]
  batch_size_val: 32
  const_max: 2
  gamma: 0.5
  n_epochs_warmup: 50
  num_workers: 12
  n_epochs: 500
  early_stop_patience: 10
  reduce_lr_patience: 5
  accumulate_batches: 1
  gradient_clip: 50000
  save_top_k: 1
  median_window: 7
  ema_factor: 0.999
  self_sup_loss: mse
  backend:
data:
  synth_folder: "/home/scornell/dcase21/egs/iterative_sed_sep/new_synth/audio/train/synthetic21_train/soundscapes_16k/"
  synth_tsv: "/home/scornell/dcase21/egs/iterative_sed_sep/new_synth/metadata/train/synhtetic21_train/soundscapes.tsv"
  weak_folder: "/home/scornell/dcase/dataset/audio/train/weak_16k/"
  weak_tsv: "/home/scornell/dcase/dataset/metadata/train/weak.tsv"
  unlabeled_folder: "/home/scornell/dcase/dataset/audio/train/unlabel_in_domain_16k/"
  val_folder: "/home/scornell/dcase/dataset/audio/validation_16k/"
  val_tsv: "/home/scornell/dcase/dataset/metadata/validation/validation.tsv"
  audio_max_len: 10
  fs: 16000
  net_subsample: 4
opt:
  lr: 0.001
feats:
  n_mels: 128
  n_filters: 2048
  kernel_size: 2048
  stride: 256
  sample_rate: 16000
